// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// flexiplex
Rcpp::IntegerVector flexiplex(Rcpp::List r_segments, Rcpp::List r_barcode_groups, int max_flank_editdistance, Rcpp::StringVector reads_in, Rcpp::String reads_out, Rcpp::String stats_out, Rcpp::String bc_out, bool reverseCompliment, int n_threads);
RcppExport SEXP _flexiplexR_flexiplex(SEXP r_segmentsSEXP, SEXP r_barcode_groupsSEXP, SEXP max_flank_editdistanceSEXP, SEXP reads_inSEXP, SEXP reads_outSEXP, SEXP stats_outSEXP, SEXP bc_outSEXP, SEXP reverseComplimentSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type r_segments(r_segmentsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type r_barcode_groups(r_barcode_groupsSEXP);
    Rcpp::traits::input_parameter< int >::type max_flank_editdistance(max_flank_editdistanceSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type reads_in(reads_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type reads_out(reads_outSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type stats_out(stats_outSEXP);
    Rcpp::traits::input_parameter< Rcpp::String >::type bc_out(bc_outSEXP);
    Rcpp::traits::input_parameter< bool >::type reverseCompliment(reverseComplimentSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(flexiplex(r_segments, r_barcode_groups, max_flank_editdistance, reads_in, reads_out, stats_out, bc_out, reverseCompliment, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flexiplexR_flexiplex", (DL_FUNC) &_flexiplexR_flexiplex, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_flexiplexR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
