# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcpp port of flexiplex
#'
#' @description demultiplex reads with flexiplex. For a detailed description
#' see documentation for the original flexiplex:
#' https://davidsongroup.github.io/flexiplex
#'
#' @param r_segments R list of FlexiplexSegment S4 objects
#' @param r_barcode_groups R list of FlexiplexGroup S4 objects
#' @param max_flank_editdistance maximum edit distance for flanking sequences
#' @param reads_in input FASTQ or FASTA file path(s)
#' @param reads_out output file for demultiplexed reads
#' @param stats_out output file for per-read demultiplex statistics
#' @param bc_out output file for barcode counts
#' @param reverseCompliment whether to reverse complement reads after demultiplexing
#' @param n_threads number of threads
#' @return IntegerVector with read counts (total, demultiplexed, single match, chimera)
#' @export
flexiplex <- function(r_segments, r_barcode_groups, max_flank_editdistance, reads_in, reads_out, stats_out, bc_out, reverseCompliment, n_threads) {
    .Call('_Rflexiplex_flexiplex', PACKAGE = 'Rflexiplex', r_segments, r_barcode_groups, max_flank_editdistance, reads_in, reads_out, stats_out, bc_out, reverseCompliment, n_threads)
}

